name: self-host-amd64-build

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'package name'
        required: true
        default: 'openlitespeed'
        type: choice
        options:
          - '"openlitespeed"'
      version:
        description: 'version number'
        type: number
      revision:
        description: 'revision number'
        type: number        
      distro:
        description: 'distro'
        required: true
        default: '9'
        type: choice
        options:
          - '"9"'
          - '"8"'
          - '"10"'          
          - '"10","9","8"'

jobs:
  package:
    runs-on: [self-hosted, linux, x64]
    container:
      image: eggcold/centos-build
      options: --user root --cap-add SYS_ADMIN --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    strategy:
      matrix:
        package: ${{ fromJSON(format('[{0}]', inputs.package)) }}
        distro: ${{ fromJSON(format('[{0}]', inputs.distro)) }}
      fail-fast: true
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
      - name: build with ${{ github.head_ref || github.ref_name }} branch
        run: |
            bash build.sh ${{ matrix.package }} ${{ matrix.distro }} x86_64 --push
        env:
          BUILD_KEY: ${{ secrets.BUILD_KEY }}
          version: ${{ inputs.version }}
          revision: ${{ inputs.revision }}
